# to render the website I can use terminal and issue "quarto render"

project:
  type: website

website:
  title: "GZEL"
  #site-url: https://nasa-openscapes.github.io/
  favicon: images/favicon.png  
  reader-mode: false
#  google-analytics:
#  cookie-consent: true
   
  page-footer: 
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/), with theme from [vetiver](https://github.com/rstudio/vetiver.rstudio.com)"
    left: "&copy; CC-By Giuliano Colosimo"
 
  navbar:
    title: " " # used to have only the icon as home button
    logo: images/favicon.png
    #href: https://openscapes.org
    right:
    - text: "About"
      href: about.qmd
    - text: "Team"
      href: champions.qmd
    - text: "Publications"
      href: publications
    - text: "Partners"
      href: partners.qmd
    - text: "Contact"
      href: contact.qmd
      
  search: 
   location: navbar
   type: overlay

format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css
    toc: false
#    toc-title: Contents
#    toc-location: left
  



# old _site.yml content below for comparison while converting to Quarto
#
# name: "."
# title: "NASA-Openscapes"
# description: |
#   NASA-Openscapes
# favicon: images/openscapes_hex.png  
# output_dir: "docs"
# navbar:
#   logo: images/openscapes_hex.png
#   href: https://openscapes.org
#   right:
#     - text: "Home"
#       href: index.html
#     - text: "About"
#       href: about.html
#     - text: "Mentors"
#       href: mentors.html
#     - text: "Champions"
#       href: champions.html 
#     - text: "Tutorials"
#       href: tutorials.html 
#     - text: "Events"
#       href: events.html
#     - icon: fab fa-twitter
#       href: https://twitter.com/openscapes
#     - icon: fab fa-github
#       href: https://github.com/nasa-openscapes
# output: distill::distill_article
# theme: theme.css
